### ISSUE TITLE
youtubedl is downloading in appdata\youtubedl folder

### ISSUE THREAD

**Issue by amitsax** [GhostWriters/DockSTARTer#1209]
# Bug report

**Describe the bug**
youtubedl - downloading in appdata\youtubedl folder. Even when the output template variables are set

**To Reproduce**
using default compose - without any overrides.

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian]

**Additional context**
Docker image does not seem to care for the YDL_ environment variable:
      - YDL_OUTPUT_TEMPLATE=${YOUTUBEDL_OUTPUT_TEMPLATE}

**Comment by amitsax** [comment]
When I tried to redirect config.yml to appdata folder using - 
YDL_CONFIG_PATH=/youtube-dl/config.yml

I get these errors:

Traceback (most recent call last):
  File "/usr/src/app/./youtube-dl-server.py", line 10, in <module>
    from ydl_server.logdb import JobsDB, Job, Actions, JobType
  File "/usr/src/app/ydl_server/logdb.py", line 6, in <module>
    from ydl_server.config import app_config
  File "/usr/src/app/ydl_server/config.py", line 14, in <module>
    app_config = load_config(config_path)
  File "/usr/src/app/ydl_server/config.py", line 10, in load_config
    config = yaml.load(configfile, Loader=yaml.SafeLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "/youtube-dl/config.yml", line 8, column 1

**Comment by angrycuban13** [comment]
There's nothing we can do on our end. You'll need to open an issue with the maintainer that is referenced on our [docs](https://dockstarter.com/apps/youtubedl). From my experience, he's very responsive and helpful.
